### ISSUE TITLE
unknown type in cursor: [object]

### ISSUE THREAD

**Issue by mividtim** [benjamin658/typeorm-cursor-pagination#16]
Hi there! This library is awesome. It's working great for most use cases I've encountered. However, I'm getting a weird error from the internals of the library occasionally when querying against test fixtures that were inserted into my local database by other tests prior to my test running. The column on which I'm trying to paginate has the PG type `timestamp`.

The entity is defined as follows:
```
    @Column({
        type: 'timestamp',
        nullable: true,
    })
    videoDisplayTime!: Date | null;
```

Here's the error coming out of the test run, with internals snipped out.
```
    Error: unknown type in cursor: [object]Mon Nov 23 2020 18:23:15 GMT+0000 (Coordinated Universal Time),at Object.encodeByType ([snip]/node_modules/typeorm-cursor-pagination/src/utils.ts:23:13),at payload.paginationKeys.map ([snip]/node_modules/typeorm-cursor-pagination/src/Paginator.ts:178:21),at Array.map (<anonymous>),at Paginator.encode ([snip]/node_modules/typeorm-cursor-pagination/src/Paginator.ts:176:41),at Paginator.<anonymous> ([snip]/node_modules/typeorm-cursor-pagination/src/Paginator.ts:92:35),at Generator.next (<anonymous>),at fulfilled ([snip]/node_modules/typeorm-cursor-pagination/lib/Paginator.js:5:58),at process._tickCallback (internal/process/next_tick.js:68:7)
    --
    body: {
      "status": 500,
      "errorName": "Error",
      "message": "unknown type in cursor: [object]Mon Nov 23 2020 18:23:15 GMT+0000 (Coordinated Universal Time)",
      "stack": [
        "at Object.encodeByType ([snip]/node_modules/typeorm-cursor-pagination/src/utils.ts:23:13)",
        "at payload.paginationKeys.map ([snip]/node_modules/typeorm-cursor-pagination/src/Paginator.ts:178:21)",
        "at Array.map (<anonymous>)",
        "at Paginator.encode ([snip]/node_modules/typeorm-cursor-pagination/src/Paginator.ts:176:41)",
        "at Paginator.<anonymous> ([snip]/node_modules/typeorm-cursor-pagination/src/Paginator.ts:92:35)",
        "at Generator.next (<anonymous>)",
        "at fulfilled ([snip]/node_modules/typeorm-cursor-pagination/lib/Paginator.js:5:58)",
        "at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
```

Any ideas on what I we may be doing wrong would be greatly appreciated!

**Comment by benjamin658** [comment]
Hi @mividtim , thanks for reporting the issue.

The library use Reflect.getMetadata(design:type...) to evaluate the type of specify pagination keys before `encode` a cursor.

I have tried to reproduce an issue, however everything is working fine:

```
import "reflect-metadata";
import { Entity, Column } from 'typeorm';

@Entity()
class Demo {
  @Column({
    type: 'timestamp',
    nullable: true,
  })
  videoDisplayTime!: Date | null;
}

console.log(Reflect.getMetadata('design:type', Demo.prototype, 'videoDisplayTime').name.toLowerCase()); // date
```

Could you provide more information about your runtime environment (version of typescript, ts-node, etc...)?

**Comment by mividtim** [comment]
Hi there. Thanks for getting back so quickly. We're running `"typescript": "3.7.2"`, `"typeorm": "0.2.20"`, `"ts-node": "8.4.1"`, `"typeorm-cursor-pagination": "0.4.1"`, and `typeorm-naming-strategies": "1.1.0"`. We use `SnakeNamingStrategy` for our table and column names... Not that I think that's relevant. We run all of this in the context of NestJS 6.8.4.

**Comment by mividtim** [comment]
NodeJS 10.15.3, yarn 1.16.0, and postgres 11.2.

**Comment by benjamin658** [comment]
I have tried the same version of these dependencies, and everything is working fine.

Could you share a piece of code that using this lib?

**Comment by mividtim** [comment]
I set up a contrived example. I believe the issue is with the naming strategy. This pagination library doesn't seem to use the naming strategy set in the TypeOrm configuration to derive proper column names for its pagination keys.

https://github.com/mividtim/pagination-test

Repro steps:
- Clone the repo.
- Run `yarn` or `npm install`.
- Create a local DB and a PG user/password for the sample to own.
- Copy `sample.env` to `.env`.
- Edit the values in `.env` to point to your local DB
- Run `yarn start:dev`
- Hit http://localhost:3000 to generate the DB table. The output should be an object with an empty `construed` array.
- Run `yarn migration:up` to populate the `construed` table with some test data.
- Refresh http://localhost:3000 to see the new data (7 values in the `construed` property)
- Hit http://localhost:3000?limit=3 to run into the error.

**Comment by benjamin658** [comment]
@mividtim thanks for the steps to reproduce an error.

I will try to fix it in my free time, if you already know how to fix it, please give me some hints or feel free to send a PR.

**Comment by mabilbao** [comment]
Hey guys! it's happening exactly the same. Any updates about it?

Thank you! 😄

**Comment by mividtim** [comment]
Hey there! No update. I basically skipped cursor pagination and am using page lengths and numbers, which is inferior, but workable if your data doesn't move fast. I wish this worked, but I didn't invest the time to make it work.

**Comment by judehunter** [comment]
it's a shame this is still an issue...
unfortunately this makes this library unusable to me

**Comment by benjamin658** [comment]
Hey guys, sorry for the late reply.

@mividtim @judehunter actually I have fixed the naming strategy issue a few months ago, 
if you don't mind giving it a try, please upgrade to v0.6.0.

cc228793e33697d97b158d2a44c094a11951b09e 
c2dcc64d49cd5f34e869418deaa39f6f55df9559

#19

**Comment by judehunter** [comment]
@benjamin658 at the time of my comment (9 days ago), I was using the latest version.
It was still an issue for me.

I might be able to provide some more detail later, but I have since switched to limit/offset pagination instead.

**Comment by benjamin658** [comment]
Hi @judehunter, thanks for your help.

Since I still cannot reproduce the issue, it would be great if you can provide some more details.

By the way, PR for fixing this issue is welcome.

**Comment by benjamin658** [comment]
Hi @mabilbao @mividtim @judehunter @miohtama , 

I think I finally found the root cause, it's ts-node issue: https://github.com/TypeStrong/ts-node/issues/511

For some reason ts-node Reflect.getMetadata of `Date` reflection is broken, it returns Object instead of Date.
Currently you can use  the `--type-check` flag to workaround if you are using `ts-node` to run you app.

I will try to fix the function https://github.com/benjamin658/typeorm-cursor-pagination/blob/28f35cb8819ea3b4270a2f000505c0f74aad9c5a/src/utils.ts#L9 to handle unexpected reflection issue.

**Comment by mividtim** [comment]
We use tsc to compile, and run with node itself, and I was seeing object from the reflect call...

**Comment by benjamin658** [comment]
Sorry to keep you waiting so long.

I just fixed the issue, please upgrade to v0.6.1.

**Comment by nitesh-01** [comment]
[1] Error: unknown type in cursor: [boolean]true
[1]     at Object.encodeByType (/home/nitesh/WebstormProjects/tw-backend/node_modules/typeorm-cursor-pagination/lib/utils.js:36:11)
[1]     at /home/nitesh/WebstormProjects/tw-backend/dist/utils/paginator/pagination.js:113:35
[1]     at Array.map (<anonymous>)
[1]     at Paginator.encode (/home/nitesh/WebstormProjects/tw-backend/dist/utils/paginator/pagination.js:111:14)
[1]     at Paginator.paginate (/home/nitesh/WebstormProjects/tw-backend/dist/utils/paginator/pagination.js:45:41)
[1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1]     at async PostsService.getAllPosts (/home/nitesh/WebstormProjects/tw-backend/dist/services/posts.service.js:159:56)
[1]     at async PostsController.all (/home/nitesh/WebstormProjects/tw-backend/dist/controllers/posts.controller.js:14:42)


any solution for this boolean

**Comment by byteHulk** [comment]
it's a shame this is still an issue...
version 0.10.0

**Comment by mividtim** [comment]
@byteHulk This might get you a bit further down the road... https://github.com/mividtim/typeorm-cursor-pagination

**Comment by mividtim** [comment]
Hmm, maybe not. I don't see my commit that fixed the issue. :-( I long lost that computer.

**Comment by kprice-ae** [comment]
Having the same issue mentioned in https://github.com/benjamin658/typeorm-cursor-pagination/issues/16#issuecomment-927576534

does not work with booleans or enum types
